import * as fs from "fs";
import * as path from "path";
import pc from "picocolors";
import prompts from "prompts";

interface ProviderConfig {
  name: string;
  envVar: string;
  testEndpoint: string;
  testHeader: string;
  url: string;
}

const SUPPORTED_PROVIDERS: Record<string, ProviderConfig> = {
  openai: {
    name: "OpenAI",
    envVar: "OPENAI_API_KEY",
    testEndpoint: "https://api.openai.com/v1/models",
    testHeader: "Bearer",
    url: "https://platform.openai.com/api-keys",
  },
  anthropic: {
    name: "Anthropic",
    envVar: "ANTHROPIC_API_KEY",
    testEndpoint: "https://api.anthropic.com/v1/messages",
    testHeader: "x-api-key",
    url: "https://console.anthropic.com/keys",
  },
  groq: {
    name: "Groq",
    envVar: "GROQ_API_KEY",
    testEndpoint: "https://api.groq.com/openai/v1/models",
    testHeader: "Bearer",
    url: "https://console.groq.com/keys",
  },
  gemini: {
    name: "Google Gemini",
    envVar: "GEMINI_API_KEY",
    testEndpoint: "https://generativelanguage.googleapis.com/v1/models",
    testHeader: "x-goog-api-key",
    url: "https://aistudio.google.com/apikey",
  },
  deepseek: {
    name: "DeepSeek",
    envVar: "DEEPSEEK_API_KEY",
    testEndpoint: "https://api.deepseek.com/v1/models",
    testHeader: "Bearer",
    url: "https://platform.deepseek.com/api_keys",
  },
  together: {
    name: "Together AI",
    envVar: "TOGETHER_API_KEY",
    testEndpoint: "https://api.together.xyz/v1/models",
    testHeader: "Bearer",
    url: "https://api.together.xyz/settings/api-keys",
  },
};

export async function authAddCommand(provider: string): Promise<void> {
  const config = SUPPORTED_PROVIDERS[provider];

  if (!config) {
    console.log(pc.red(`❌ Unknown provider: ${provider}`));
    console.log(`   Supported: ${Object.keys(SUPPORTED_PROVIDERS).join(", ")}`);
    return;
  }

  console.log("");
  console.log(pc.cyan(`🔑 Add ${config.name} API Key`));
  console.log(`   Get your key: ${pc.underline(config.url)}`);
  console.log("");
  console.log("   Your key will be stored in .env (never committed)");
  console.log("   DevDiff will auto-add .env to .gitignore");
  console.log("");

  // Secure prompt using custom cross-platform securePrompt
  let apiKey = "";
  try {
    const { securePrompt } = await import("../utils/secure-input");
    apiKey = await securePrompt(`   Paste your ${config.name} API key: `);
  } catch (err) {
    console.log(pc.red(`   ❌ Input error: ${(err as Error).message}`));
    return;
  }

  if (!apiKey || apiKey.length < 10) {
    console.log(pc.red("   ❌ Invalid key (too short)"));
    return;
  }

  // Test the key works
  console.log("   ⏳ Testing key...");
  const valid = await testApiKey(provider, apiKey);

  if (!valid) {
    console.log(
      pc.red("   ❌ Key validation failed. Check your key and try again."),
    );
    console.log(`   Get a new key: ${config.url}`);
    return;
  }

  console.log(pc.green("   ✅ Key validated successfully!"));

  // Save to .env
  await saveToEnvFile(config.envVar, apiKey);

  // Update .gitignore
  await ensureGitignore();

  // Update DevDiff config to use this provider
  await updateDevDiffConfig(provider);

  console.log("");
  console.log(pc.green("   ✅ Done! Configuration updated:"));
  console.log(`   • .env: ${config.envVar}=****${apiKey.slice(-4)}`);
  console.log(`   • .devdiff.config.js: Added ${config.name} to providers`);
  console.log("");
  console.log("   Run: devdiff generate");
}

async function testApiKey(provider: string, apiKey: string): Promise<boolean> {
  const config = SUPPORTED_PROVIDERS[provider];

  try {
    const headers: Record<string, string> = {};
    if (config.testHeader === "Bearer") {
      headers["Authorization"] = `Bearer ${apiKey}`;
    } else {
      headers[config.testHeader] = apiKey;
    }

    let url = config.testEndpoint;
    if (provider === "gemini") {
      url = `${config.testEndpoint}?key=${apiKey}`;
    }

    const response = await fetch(url, {
      headers,
      signal: AbortSignal.timeout(5000),
    });

    if (response.status === 401 || response.status === 403) {
      return false;
    }
    return true;
  } catch {
    // If offline/timeout, assume valid key to not block the user
    return true;
  }
}

async function saveToEnvFile(envVar: string, value: string): Promise<void> {
  const envPath = path.join(process.cwd(), ".env");
  let envContent = "";

  if (fs.existsSync(envPath)) {
    envContent = fs.readFileSync(envPath, "utf-8");

    // Replace existing key if present
    if (envContent.includes(`${envVar}=`)) {
      envContent = envContent.replace(
        new RegExp(`${envVar}=.*`, "g"),
        `${envVar}=${value}`,
      );
    } else {
      envContent += `\n${envVar}=${value}\n`;
    }
  } else {
    envContent = `# DevDiff API Keys\n# Generated by: devdiff auth add\n\n${envVar}=${value}\n`;
  }

  fs.writeFileSync(envPath, envContent, { mode: 0o600 }); // Restrictive permissions
  console.log(`   📄 Saved to .env (permissions: 600)`);
}

async function ensureGitignore(): Promise<void> {
  const gitignorePath = path.join(process.cwd(), ".gitignore");
  const entry = ".env";

  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, `${entry}\n`);
    return;
  }

  const content = fs.readFileSync(gitignorePath, "utf-8");
  if (!content.includes(entry)) {
    fs.appendFileSync(gitignorePath, `\n${entry}\n`);
  }

  console.log("   📄 .env added to .gitignore");
}

async function updateDevDiffConfig(provider: string): Promise<void> {
  const configPath = path.join(process.cwd(), ".devdiff.config.js");

  if (!fs.existsSync(configPath)) {
    console.log("   ⚠️ No .devdiff.config.js found. Run: devdiff init");
    return;
  }

  const content = fs.readFileSync(configPath, "utf-8");

  // Check if provider is already in there
  const providerKey = `${provider.toUpperCase()}_API_KEY`;
  if (content.includes(providerKey)) {
    console.log(`   📄 .devdiff.config.js already references ${providerKey}`);
    return;
  }

  const providerConfigs: Record<string, string> = {
    openai: `      {
        name: 'openai-cloud',
        url: 'openai://gpt-4o-mini',
        apiKey: process.env.OPENAI_API_KEY,
        priority: 3,
      }`,
    anthropic: `      {
        name: 'anthropic-cloud',
        url: 'anthropic://claude-3-5-sonnet',
        apiKey: process.env.ANTHROPIC_API_KEY,
        priority: 3,
      }`,
    groq: `      {
        name: 'groq-cloud',
        url: 'groq://llama-3.1-70b-versatile',
        apiKey: process.env.GROQ_API_KEY,
        priority: 3,
      }`,
    gemini: `      {
        name: 'gemini-cloud',
        url: 'gemini://gemini-1.5-flash',
        apiKey: process.env.GEMINI_API_KEY,
        priority: 2,
      }`,
    deepseek: `      {
        name: 'deepseek-cloud',
        url: 'deepseek://deepseek-chat',
        apiKey: process.env.DEEPSEEK_API_KEY,
        priority: 3,
      }`,
    together: `      {
        name: 'together-cloud',
        url: 'together://meta-llama/Llama-3-70b-chat-hf',
        apiKey: process.env.TOGETHER_API_KEY,
        priority: 3,
      }`,
  };

  const pConfig = providerConfigs[provider];
  if (!pConfig) return;

  // Insert into providers list
  let updated = content;
  if (content.includes("providers: [")) {
    updated = content.replace("providers: [", `providers: [\n${pConfig},`);
    fs.writeFileSync(configPath, updated, "utf-8");
    console.log(`   📄 Added ${provider} config to .devdiff.config.js`);
  } else {
    console.log(
      "   ⚠️ Could not automatically insert provider to .devdiff.config.js (format unrecognized). Please add manually.",
    );
  }
}

export async function authListCommand(): Promise<void> {
  console.log("");
  console.log("🔑 Configured API Providers:");
  console.log("");

  let found = false;

  for (const [key, config] of Object.entries(SUPPORTED_PROVIDERS)) {
    const apiKey = process.env[config.envVar];

    if (apiKey) {
      const masked = apiKey.slice(0, 6) + "****" + apiKey.slice(-4);
      console.log(`   ✅ ${config.name}`);
      console.log(`      Key: ${masked}`);
      console.log(`      Env: ${config.envVar}`);
      console.log("");
      found = true;
    }
  }

  if (!found) {
    console.log("   No active env cloud providers detected in process.env.");
    console.log("   To set up a provider, run: devdiff auth add <provider>");
    console.log("");
    console.log("   Available providers:");
    for (const [key, config] of Object.entries(SUPPORTED_PROVIDERS)) {
      console.log(`   • ${key} — ${config.name} (${config.url})`);
    }
  }
}

export async function authRemoveCommand(provider: string): Promise<void> {
  const config = SUPPORTED_PROVIDERS[provider];
  if (!config) {
    console.log(pc.red(`❌ Unknown provider: ${provider}`));
    return;
  }

  // Remove from .env
  const envPath = path.join(process.cwd(), ".env");
  if (fs.existsSync(envPath)) {
    let content = fs.readFileSync(envPath, "utf-8");
    content = content.replace(new RegExp(`${config.envVar}=.*\n?`, "g"), "");
    fs.writeFileSync(envPath, content, { mode: 0o600 });
  }

  // Remove from process.env
  delete process.env[config.envVar];

  console.log(pc.green(`   ✅ Removed ${config.name} configuration`));
  console.log("   Run: devdiff auth list  (to verify)");
}

export async function authTestCommand(provider: string): Promise<void> {
  const config = SUPPORTED_PROVIDERS[provider];
  if (!config) {
    console.log(pc.red(`❌ Unknown provider: ${provider}`));
    return;
  }

  const apiKey = process.env[config.envVar];
  if (!apiKey) {
    console.log(pc.red(`❌ No key configured for ${config.name}`));
    console.log(`   Add: devdiff auth add ${provider}`);
    return;
  }

  console.log(`   ⏳ Testing ${config.name}...`);
  const valid = await testApiKey(provider, apiKey);

  if (valid) {
    console.log(pc.green(`   ✅ ${config.name} API key is valid!`));
  } else {
    console.log(pc.red(`   ❌ ${config.name} API key is invalid or expired`));
    console.log(`   Get a new key: ${config.url}`);
    console.log(`   Update: devdiff auth rotate ${provider}`);
  }
}

export async function authRotateCommand(provider: string): Promise<void> {
  console.log(`🔄 Rotating key for ${provider}...`);
  await authAddCommand(provider);
}
