import { CompletenessValidator } from "./completeness-validator";
import { NaturalChangelogGenerator } from "../generators/natural-changelog";
import { ParsedDiff } from "../ai/prompts/optimized-prompts";

export interface QualityGateOptions {
  diff?: ParsedDiff;
  strictMode?: boolean;
  fallbackToTemplate?: boolean;
}

export interface QualityGateResult {
  accepted: boolean;
  reason?: string;
  details?: string[];
  action?: "retry" | "template" | "accept";
  output?: string;
  quality?: "good" | "acceptable" | "poor" | "unusable";
  metadata?: {
    originalLength: number;
    cleanedLength: number;
    completenessIssues: string[];
    hallucinationFindings?: string[];
  };
}

export class OutputQualityGate {
  /**
   * Process AI output through quality gates before accepting.
   * Rejects incomplete, low-quality, or hallucinated output.
   */
  static async process(rawOutput: string, options: QualityGateOptions = {}): Promise<QualityGateResult> {
    // ── Gate 1: Completeness ──
    const completeness = CompletenessValidator.validate(rawOutput);

    if (completeness.quality === "unusable") {
      return {
        accepted: false,
        reason: "Output failed completeness check",
        details: completeness.issues,
        action: "retry",
      };
    }

    // ── Gate 2: Remove AI-sounding language ──
    let cleaned = NaturalChangelogGenerator.sanitize(rawOutput);

    // ── Gate 3: Remove defensive headers ──
    cleaned = this.removeDefensiveHeaders(cleaned);

    // ── Gate 4: Verify minimum quality ──
    const quality = this.assessContentQuality(cleaned);

    if (quality === "poor") {
      return {
        accepted: false,
        reason: "Output quality below threshold",
        action: options.fallbackToTemplate ? "template" : "retry",
      };
    }

    // ── Gate 5: Hallucination check ──
    let hallucinationFindings: string[] | undefined = undefined;
    if (options.diff) {
      const hallucinationCheck = this.checkHallucinations(cleaned, options.diff);

      if (hallucinationCheck.hasHallucinations) {
        hallucinationFindings = hallucinationCheck.findings;
        if (options.strictMode) {
          return {
            accepted: false,
            reason: "Potential hallucinations detected",
            details: hallucinationCheck.findings,
            action: "retry",
          };
        }
      }
    }

    return {
      accepted: true,
      output: cleaned,
      quality,
      metadata: {
        originalLength: rawOutput.length,
        cleanedLength: cleaned.length,
        completenessIssues: completeness.issues,
        hallucinationFindings,
      },
    };
  }

  /**
   * Remove defensive headers that undermine trust
   */
  public static removeDefensiveHeaders(text: string): string {
    return text
      .replace(/#+\s*---\s*DevDiff.*?---\s*\n*/gi, "")
      .replace(/#+\s*The section below contains AI-generated.*?\n*/gi, "")
      .replace(/#+\s*Feel free to edit or remove it.*?\n*/gi, "")
      .replace(/#+\s*AI-generated changelog.*?\n*/gi, "")
      .replace(/#+\s*Generated by DevDiff.*?\n*/gi, "")
      .trim();
  }

  /**
   * Quick content quality assessment
   */
  public static assessContentQuality(text: string): "good" | "acceptable" | "poor" {
    if (text.length < 30) return "poor";

    const sentences = text.split(/[.!?]+/).filter((s) => s.trim().length > 0);
    const hasListItems = /^#{1,6}\s|^\s*[-*]\s/m.test(text);

    if (sentences.length < 3 && !hasListItems) return "poor";

    // Check for AI-sounding patterns
    const aiPatterns = [
      /The (provided|following) (code|snippet)/i,
      /Here('s| is) (a |an )?(breakdown|summary)/i,
      /appears to/i,
      /seems to/i,
    ];

    const aiPatternCount = aiPatterns.filter((p) => p.test(text)).length;
    const avgSentenceLength = sentences.length > 0 ? text.length / sentences.length : text.length;

    if (aiPatternCount >= 3) return "poor";
    if (avgSentenceLength > 200) return "acceptable"; // Very long sentences
    if (aiPatternCount === 0 && (sentences.length >= 3 || hasListItems)) return "good";

    return "acceptable";
  }

  /**
   * Quick hallucination check
   */
  public static checkHallucinations(
    text: string,
    diff: ParsedDiff
  ): {
    hasHallucinations: boolean;
    findings: string[];
  } {
    const findings: string[] = [];
    const actualFiles = new Set((diff.files || []).map((f) => f.path));

    // Check for referenced files that don't exist
    const filePattern = /`([^`]+\.(ts|js|tsx|jsx|py|go|rs|java|rb|php|cs|swift|kt|dart))`/gi;
    let match;

    while ((match = filePattern.exec(text)) !== null) {
      const referencedFile = match[1];

      // Check if this file exists in the diff
      const exists = Array.from(actualFiles).some(
        (f) => f.includes(referencedFile) || f.endsWith(referencedFile)
      );

      if (!exists) {
        findings.push(`Referenced file not in diff: ${referencedFile}`);
      }
    }

    return {
      hasHallucinations: findings.length > 0,
      findings,
    };
  }
}
