import fs from "fs";
import path from "path";

const FROM_VERSION = "1.0.5";
const TO_VERSION = "1.0.6";
const DATE_STR = new Date().toISOString().split("T")[0];

console.log(`Bumping version from ${FROM_VERSION} to ${TO_VERSION}...`);

// 1. Find all package.json files and update them
function updatePackageJsons() {
  const pkgs = [
    "package.json",
    "packages/antigravity/package.json",
    "packages/cli/package.json",
    "packages/connectors/package.json",
    "packages/core/package.json",
    "packages/create-devdiff-app/package.json",
    "packages/gateway/package.json",
    "packages/integrations/openclaw/package.json",
    "packages/mcp/package.json",
    "packages/personas/package.json",
    "packages/plugin-sdk/package.json",
    "packages/vite-plugin/package.json",
    "packages/vscode/package.json",
    "packages/web-dashboard/package.json",
  ];

  for (const pkgFile of pkgs) {
    const pkgPath = path.resolve(pkgFile);
    if (!fs.existsSync(pkgPath)) {
      console.warn(`Warning: Package file ${pkgFile} not found.`);
      continue;
    }
    let content = fs.readFileSync(pkgPath, "utf8");
    // Replace "version": "1.0.5"
    content = content.replace(/"version":\s*"1.0.5"/, `"version": "1.0.6"`);
    fs.writeFileSync(pkgPath, content, "utf8");
    console.log(`Updated ${pkgFile}`);
  }
}

// 2. Update config-autocomplete.ts
function updateConfigAutocomplete() {
  const file = path.resolve(
    "packages/cli/src/autocomplete/config-autocomplete.ts",
  );
  if (fs.existsSync(file)) {
    let content = fs.readFileSync(file, "utf8");
    content = content.replace(
      /Configuration schema for DevDiff v1\.0\.5/g,
      "Configuration schema for DevDiff v1.0.6",
    );
    content = content.replace(/"default":\s*"1\.0\.5"/g, '"default": "1.0.6"');
    content = content.replace(
      /"examples":\s*\["1\.0\.0",\s*"1\.0\.5"\]/g,
      '"examples": ["1.0.0", "1.0.6"]',
    );
    fs.writeFileSync(file, content, "utf8");
    console.log(`Updated config-autocomplete.ts`);
  }
}

// 3. Update version.ts
function updateVersionTs() {
  const file = path.resolve("packages/cli/src/commands/version.ts");
  if (fs.existsSync(file)) {
    let content = fs.readFileSync(file, "utf8");
    // Replace hardcoded "1.0.5" defaults
    content = content.replace(/"1\.0\.5"/g, '"1.0.6"');

    // Add v1.0.6 entry to the EMBEDDED_CHANGELOG
    const v106Changelog = `
v1.0.6 (${DATE_STR})
  + Standardized CLI option flag order (short options first)
  + Handled Commander Command argument propagation in index.ts
  + Dynamically increased dry-run performance test threshold on Windows
  + Corrected playground port conflict auto-fallback handling
`.trim();

    content = content.replace(
      /const EMBEDDED_CHANGELOG = `([\s\S]*?)`.trim\(\);/,
      (match, p1) => {
        return `const EMBEDDED_CHANGELOG = \`\n${v106Changelog}\n\n${p1.trim()}\n\`.trim();`;
      },
    );

    fs.writeFileSync(file, content, "utf8");
    console.log(`Updated version.ts`);
  }
}

// 4. Update command-registry.ts
function updateCommandRegistry() {
  const file = path.resolve("packages/cli/src/registry/command-registry.ts");
  if (fs.existsSync(file)) {
    let content = fs.readFileSync(file, "utf8");
    content = content.replace(/since:\s*'1\.0\.5'/g, "since: '1.0.6'");
    fs.writeFileSync(file, content, "utf8");
    console.log(`Updated command-registry.ts`);
  }
}

// 5. Update changelog-fallback.ts
function updateChangelogFallback() {
  const file = path.resolve(
    "packages/core/src/generators/changelog-fallback.ts",
  );
  if (fs.existsSync(file)) {
    let content = fs.readFileSync(file, "utf8");
    content = content.replace(
      /Generated by DevDiff v1\.0\.5/g,
      "Generated by DevDiff v1.0.6",
    );
    fs.writeFileSync(file, content, "utf8");
    console.log(`Updated changelog-fallback.ts`);
  }
}

// 6. Update mcp/src/server-v2.ts
function updateMcpServer() {
  const file = path.resolve("packages/mcp/src/server-v2.ts");
  if (fs.existsSync(file)) {
    let content = fs.readFileSync(file, "utf8");
    content = content.replace(/version:\s*'1\.0\.5'/g, "version: '1.0.6'");
    fs.writeFileSync(file, content, "utf8");
    console.log(`Updated mcp server-v2.ts`);
  }
}

// 7. Update CHANGELOG.md and docs/changelog.md
function updateChangelogs() {
  const v106Markdown = `
## [1.0.6] — ${DATE_STR} · Windows & Command Argument Hardening

The **Windows & Command Argument Hardening** release resolves critical command execution, argument parsing, option ordering, and environment performance behaviors:
- **Commander Argument Parsing**: Filtered out Command class instances from execution argument arrays, preventing CLI parameter mismatches.
- **Option Flag Standardization**: Re-ordered option flags so short options are parsed before long options consistently (e.g. \`-p, --persona\`).
- **Windows Process Performance**: Tuned test threshold bounds to accommodate child process spawning time on Windows file structures.
- **Port Reuse Handlers**: Verified playground listen fallback routines handling port collisions natively.
`.trim();

  // Root CHANGELOG.md
  const changelogPath = path.resolve("CHANGELOG.md");
  if (fs.existsSync(changelogPath)) {
    let content = fs.readFileSync(changelogPath, "utf8");
    content = content.replace(
      /# Changelog\n\nAll notable changes to DevDiff are documented here\./,
      (match) => {
        return `${match}\n\n${v106Markdown}\n\n---`;
      },
    );
    fs.writeFileSync(changelogPath, content, "utf8");
    console.log(`Updated CHANGELOG.md`);
  }

  // docs/changelog.md
  const docsChangelogPath = path.resolve("docs/changelog.md");
  if (fs.existsSync(docsChangelogPath)) {
    let content = fs.readFileSync(docsChangelogPath, "utf8");
    content = content.replace(
      /# Changelog\n\nAll notable changes to DevDiff are documented here\./,
      (match) => {
        return `${match}\n\n${v106Markdown}\n\n---`;
      },
    );
    fs.writeFileSync(docsChangelogPath, content, "utf8");
    console.log(`Updated docs/changelog.md`);
  }
}

// 8. Update test suite
function updateTestSuite() {
  const file = path.resolve("test/stress/full-suite.sh");
  if (fs.existsSync(file)) {
    let content = fs.readFileSync(file, "utf8");
    content = content.replace(/DEVDIFF v1\.0\.5/g, "DEVDIFF v1.0.6");
    fs.writeFileSync(file, content, "utf8");
    console.log(`Updated test/stress/full-suite.sh`);
  }
}

// Run updates
updatePackageJsons();
updateConfigAutocomplete();
updateVersionTs();
updateCommandRegistry();
updateChangelogFallback();
updateMcpServer();
updateChangelogs();
updateTestSuite();

console.log("Version bump to 1.0.6 complete!");
